apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpserver-gw
  namespace: httpmesh
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - httpserver.am2901.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls: 
      credentialName: httpserver
      mode: SIMPLE
